import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
// import Script from 'next/script'

export default function Home() {
  // ·
  // │
  // │
  // │
  // ╰────
  // ✓
  // ×
  // ╭──
  // │
  // │ 
  // console.log(styles)
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        .myImg{
          border-radius: 50%;
        }
        h2{
          font-size: 40px;
        }
        h3{
          font-size: 30px;
        }
        .dummy{
          margin: 4rem;  
        }
        // .Span{
        //   color: blue;
        //   font-size: 100px;
        //   }
          `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by Tony Daange" />
        <meta name="keywords" content="Next.js, hunting coder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/script1.js' strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='dummy'>Hunting Coder</span>
        </h1>
        <div className={styles.myImgWrap}></div>
        <Image className={styles.myImg} src="/homeimg.avif" width={310} height={207} />

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>
        {/* <div className={`${styles1.con} ${styles2.con}`}> */}
        <div>
          <h2>Latest blogs</h2>
          <div className="blogItem">
            <h3>How to Learn JavaScript in 2025?</h3>
            <p>JavaScript is the language used to logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to Learn JavaScript in 2025?</h3>
            <p>JavaScript is the language used to logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to Learn JavaScript in 2025?</h3>
            <p>JavaScript is the language used to logic for the web</p>
          </div>
        </div>
      </main>


      {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
              </a>
              </div> */}
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
